services:
  # web:
  #   environment:
  #     - REACT_APP_API_ENDPOINT=
  mongodb:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/data/db'

volumes:
  mongodb_data:
    driver: local


# mongodump --uri="mongodb+srv://aefDbUser:faizMawaid123@fmb-mhfjb.azure.mongodb.net/fmb_prod?retryWrites=true" --out=/data/backup
# mongorestore --uri="mongodb://localhost:27017" --nsFrom="fmb_prod.*" --nsTo="fmb_prod.*" --dir=/data/backup

